### ISSUE TITLE
Software can't contact webservice

### ISSUE THREAD

**Issue by cheverny** [treeDiM/StackBuilder#137]
Hi,

we can't access application anymore today. Here is the reported error :
![image](https://user-images.githubusercontent.com/24827185/65430485-50577100-de18-11e9-8cdf-af1f3c7b7e5c.png)

of course, internet connection is functional and I tested without a firewall.

Thanks in advance

**Comment by fgasnier71** [comment]
I updated the application. Your problem must be solved.

**Comment by theroyalfart** [comment]
Hi! i recently installed the application via CrossOver, but now I receive this error message.
It comes in 2 forms, either the one shown above... OR... given in this url i've uploaded here:
http://prntscr.com/pcnvzk

Could you help me out @fgasnier71 ? Pls also do understand that my technical IT lingo is not very good. Many thanks!

**Comment by fgasnier71** [comment]
This error message shows up because your computer/network firewall prevents
the application to reach our server.
If you are using the latest version you should be able to use some of
StackBuilder features (but not all) without connecting using the connect
later button.
Regards,
------------------------------------------------------------
[image: logo treedim-picador.jpg]
François GASNIER
treeDiM
1 rue des Frères Lumière
F-92500 RUEIL-MALMAISON  - FRANCE
Tél.: 09 50 04 13 60
http://www.treedim.com
------------------------------------------------------------

**Comment by theroyalfart** [comment]
Good morning to you! I checked my Macbook settings, and the Firewall is turned off (http://prntscr.com/pcq8m4). I am indeed using the latest version, but some of the software requires me to log in e.g. optimizing the best pack, and our class used that today but I couldn't get to that

**Comment by fgasnier71** [comment]
Now, I have no clue about what is going on.
I am unsure that this version (>3) of our application actually works on Apple computers.
Can other people connect the application via your network?

"Optimizing the best pack" requires accessing our online database and will not work without connecting.
Regards,

**Comment by theroyalfart** [comment]
Alternatively, would a previous version be possible for me to install? Yes, I have friends who used Bootcamp to install Windows on their MAC and it works for them. Many others have Windows laptop so it’s possible to them too. Likely could be due to my Macbook or CrossOver. Network is same for everyone.

**Comment by fgasnier71** [comment]
Features are much poorer in version 2.0  and you are better off using version 3.0 without connection.
Surprisingly, comments say that Crossover is unlikely to block services.

**Comment by theroyalfart** [comment]
I have another Windows laptop, so I downloaded it in there, and am using now. However, because it is very bulky, I try not to utilise my Windows. I have already downloaded the necessary dependencies e.g. Microsoft .NET Framework etc, but perhaps you could let me know what other dependencies are needed for your app so I can download?

**Comment by fgasnier71** [comment]
Compulsory:
* .NET framework 4.7.1.
Optional:
* MS Word to edit your reports,
* a pdf viewer () to view generated reports.
* MS Excel for project summary reports or for loading the database with an existing list of cases/pallets/bundles...
Regards,
